export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCSESS = 'GET_USERS_SUCCSESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCSESS = 'CREATE_USER_SUCCSESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST'
export const REMOVE_USER_SUCCSESS = 'REMOVE_USER_SUCCSESS'
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCSESS = 'EDIT_USER_SUCCSESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const GET_COMPANIES_REQUEST = 'GET_COMPANIES_REQUEST'
export const GET_COMPANIES_SUCCSESS = 'GET_COMPANIES_SUCCSESS'
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE'

export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST'
export const CREATE_COMPANY_SUCCSESS = 'CREATE_COMPANY_SUCCSESS'
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE'

export const REMOVE_COMPANY_REQUEST = 'REMOVE_COMPANY_REQUEST'
export const REMOVE_COMPANY_SUCCSESS = 'REMOVE_COMPANY_SUCCSESS'
export const REMOVE_COMPANY_FAILURE = 'REMOVE_COMPANY_FAILURE'

export const EDIT_COMPANY_REQUEST = 'EDIT_COMPANY_REQUEST'
export const EDIT_COMPANY_SUCCSESS = 'EDIT_COMPANY_SUCCSESS'
export const EDIT_COMPANY_FAILURE = 'EDIT_COMPANY_FAILURE'

export const SIGN_IN_AS_COMPANY_REQUEST = 'SIGN_IN_AS_COMPANY_REQUEST'
export const SIGN_IN_AS_COMPANY_SUCCESS = 'SIGN_IN_AS_COMPANY_SUCCESS'
export const SIGN_IN_AS_COMPANY_FAILURE = 'SIGN_IN_AS_COMPANY_FAILURE'

export const SIGN_IN_AS_USER_REQUEST = 'SIGN_IN_AS_USER_REQUEST'
export const SIGN_IN_AS_USER_SUCCESS = 'SIGN_IN_AS_USER_SUCCESS'
export const SIGN_IN_AS_USER_FAILURE = 'SIGN_IN_AS_USER_FAILURE'
