export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCSESS = 'GET_USERS_SUCCSESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCSESS = 'CREATE_USER_SUCCSESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST'
export const REMOVE_USER_SUCCSESS = 'REMOVE_USER_SUCCSESS'
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCSESS = 'EDIT_USER_SUCCSESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const GET_COMPANIES_REQUEST = 'GET_COMPANIES_REQUEST'
export const GET_COMPANIES_SUCCSESS = 'GET_COMPANIES_SUCCSESS'
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE'

export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST'
export const CREATE_COMPANY_SUCCSESS = 'CREATE_COMPANY_SUCCSESS'
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE'

export const ADD_USER_SOCKET_SUCCESS = 'ADD_USER_SOCKET_SUCCESS'
export const ADD_COMPANY_SOCKET_SUCCESS = 'ADD_COMPANY_SOCKET_SUCCESS'

export const REMOVE_COMPANY_REQUEST = 'REMOVE_COMPANY_REQUEST'
export const REMOVE_COMPANY_SUCCSESS = 'REMOVE_COMPANY_SUCCSESS'
export const REMOVE_COMPANY_FAILURE = 'REMOVE_COMPANY_FAILURE'

export const EDIT_COMPANY_REQUEST = 'EDIT_COMPANY_REQUEST'
export const EDIT_COMPANY_SUCCSESS = 'EDIT_COMPANY_SUCCSESS'
export const EDIT_COMPANY_FAILURE = 'EDIT_COMPANY_FAILURE'

export const SIGN_IN_AS_COMPANY_REQUEST = 'SIGN_IN_AS_COMPANY_REQUEST'
export const SIGN_IN_AS_COMPANY_SUCCESS = 'SIGN_IN_AS_COMPANY_SUCCESS'
export const SIGN_IN_AS_COMPANY_FAILURE = 'SIGN_IN_AS_COMPANY_FAILURE'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const EDIT_ORDER_REQUEST = 'EDIT_ORDER_REQUEST'
export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS'
export const EDIT_ORDER_FAILURE = 'EDIT_ORDER_FAILURE'

export const REMOVE_ORDER_REQUEST = 'REMOVE_ORDER_REQUEST'
export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS'
export const REMOVE_ORDER_FAILURE = 'REMOVE_ORDER_FAILURE'

export const GET_COMPANY_ALL_ORDERS_REQUEST = 'GET_COMPANY_ALL_ORDERS_REQUEST'
export const GET_COMPANY_ALL_ORDERS_SUCCESS = 'GET_COMPANY_ALL_ORDERS_SUCCESS'
export const GET_COMPANY_ALL_ORDERS_FAILURE = 'GET_COMPANY_ALL_ORDERS_FAILURE'

export const GET_COMPANY_DONE_ORDERS_REQUEST = 'GET_COMPANY_DONE_ORDERS_REQUEST'
export const GET_COMPANY_DONE_ORDERS_SUCCESS = 'GET_COMPANY_DONE_ORDERS_SUCCESS'
export const GET_COMPANY_DONE_ORDERS_FAILURE = 'GET_COMPANY_DONE_ORDERS_FAILURE'

export const GET_COMPANY_ACTIVE_ORDERS_REQUEST =
  'GET_COMPANY_ACTIVE_ORDERS_REQUEST'
export const GET_COMPANY_ACTIVE_ORDERS_SUCCESS =
  'GET_COMPANY_ACTIVE_ORDERS_SUCCESS'
export const GET_COMPANY_ACTIVE_ORDERS_FAILURE =
  'GET_COMPANY_ACTIVE_ORDERS_FAILURE'

export const GET_COMPANY_PENDING_ORDERS_REQUEST =
  'GET_COMPANY_PENDING_ORDERS_REQUEST'
export const GET_COMPANY_PENDING_ORDERS_SUCCESS =
  'GET_COMPANY_PENDING_ORDERS_SUCCESS'
export const GET_COMPANY_PENDING_ORDERS_FAILURE =
  'GET_COMPANY_PENDING_ORDERS_FAILURE'

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILIRE'

export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST'
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS'
export const GET_USER_ORDERS_FAILURE = 'GET_USER_ORDERS_FAILIRE'

export const SIGN_IN_AS_USER_REQUEST = 'SIGN_IN_AS_USER_REQUEST'
export const SIGN_IN_AS_USER_SUCCESS = 'SIGN_IN_AS_USER_SUCCESS'
export const SIGN_IN_AS_USER_FAILURE = 'SIGN_IN_AS_USER_FAILURE'

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const ACTIVE = 'active'
export const ALL = 'all'
export const DONE = 'done'
export const PENDING = 'pending'

export const GET_COMPANY_MORE_ALL_ORDERS_SUCCESS =
  'GET_COMPANY_MORE_ALL_ORDERS_SUCCESS'
export const GET_COMPANY_MORE_ALL_ORDERS_FAILURE =
  'GET_COMPANY_MORE_ALL_ORDERS_FAILURE'

export const GET_COMPANY_MORE_ACTIVE_ORDERS_SUCCESS =
  'GET_COMPANY_MORE_ACTIVE_ORDERS_SUCCESS'
export const GET_COMPANY_MORE_ACTIVE_ORDERS_FAILURE =
  'GET_COMPANY_MORE_ACTIVE_ORDERS_FAILURE'

export const GET_COMPANY_MORE_PENDING_ORDERS_SUCCESS =
  'GET_COMPANY_MORE_PENDING_ORDERS_SUCCESS'
export const GET_COMPANY_MORE_PENDING_ORDERS_FAILURE =
  'GET_COMPANY_MORE_PENDING_ORDERS_FAILURE'

export const GET_COMPANY_MORE_DONE_ORDERS_SUCCESS =
  'GET_COMPANY_MORE_DONE_ORDERS_SUCCESS'
export const GET_COMPANY_MORE_DONE_ORDERS_FAILURE =
  'GET_COMPANY_MORE_DONE_ORDERS_FAILURE'
export const GET_USER_DONE_ORDERS_REQUEST = 'GET_USER_DONE_ORDERS_REQUEST'
export const GET_USER_DONE_ORDERS_SUCCESS = 'GET_USER_DONE_ORDERS_SUCCESS'
export const GET_USER_DONE_ORDERS_FAILURE = 'GET_USER_DONE_ORDERS_FAILURE'
export const GET_USER_PENDING_ORDERS_REQUEST = 'GET_USER_PENDING_ORDERS_REQUEST'
export const GET_USER_PENDING_ORDERS_SUCCESS = 'GET_USER_PENDING_ORDERS_SUCCESS'
export const GET_USER_PENDING_ORDERS_FAILURE = 'GET_USER_PENDING_ORDERS_FAILURE'
